version: '1'
services:

  database:
    container_name: 'database'
    image: greys73/database
    build:
      context: .
      dockerfile: ./Dockerfile.db
    networks:
      - homelib
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql

  app:
    container_name: 'app'
    image: greys73/service-app
    build:
      context: .
      dockerfile: ./Dockerfile.app
    networks:
      - homelib
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    volumes:
      - ./src:/app/src

volumes:
  db_data:
  db_logs:
networks:
  homelib:
    driver: bridge
    name: 'homelib'
